### ISSUE TITLE
Image2 files removed

### ISSUE THREAD

**Issue by ebrehault** [collective/collective.ckeditor#48]
Hi @gotcha,

The README mention we need to declare the image2 plugin like this:
```
<element value="image2;/++resource++ckeditor/plugins/image2/plugin.js"/>
```
but this resource does not exists.

Apparently, almost all the files in the image2 folder have been removed with this commit:
https://github.com/collective/collective.ckeditor/commit/2abbce87bd2cbba34bc39e49a588531e9f77fdcb#diff-d70d722af3ed68fced490f6892651e31

I guess we just need to get the 4.5.6 version from http://ckeditor.com/addon/image2, but is there anything special we need to take care of?

**Comment by gotcha** [comment]
@ebrehault The release is supposed to hold image2 plugin. I'll need to dig why it seems to not be there.

**Comment by gotcha** [comment]
There  were two bugs:
- the way I built the new ckeditor did not support the choice between `image` and `image2` plugins.
- the latest image2 does not accept empty values for image classes, the fix demands applying an upgrade step

Fixed in new release https://pypi.python.org/pypi/collective.ckeditor/4.3.2
